### ISSUE TITLE
Archive Layout issue

### ISSUE THREAD

**Issue by wpelance** [dudaster/ele-custom-skin#213]
Hi,

I recently purchased the ele custom skin and wanted to use it to create my own look and feel so was testing it out today and I have run into an issue and not sure whats causing this.

I am trying this out for custom post type My Portfolio create using a combination of CPT UI and ACF.

If I use the default loop of elementor it works fine but when I use the custom loop this is how it shows.

Please find the image screenshots for reference
![Issue with Ele Custom Skin 1](https://user-images.githubusercontent.com/62963503/82435238-a10b9080-9ab1-11ea-8d53-6e1df1a60ef0.jpg)
![Issue with Ele Custom Skin 2](https://user-images.githubusercontent.com/62963503/82435242-a2d55400-9ab1-11ea-828c-68e6a64ce26f.jpg)

I could not publish the URL as its a live environment hence I have sent to your email temp admin credentials.

Appreciate if you can help me out, Thanks in advance. Have a great day ahead!

Regards,
Srinivas

**Comment by wpelance** [comment]
The issue is fixed. Thank you very much for the quick support provided. It's working as I need it. I appreciate all the help provided.

Thanks a Ton! Best Support Received.
Regards,
Srinivas

**Comment by dudaster** [comment]
The problem was with astra theme. A patch for this problem will be released in the next version.

**Comment by Basv964** [comment]
I experience the same problem. Also after the astra update from this weekend the layout still shows the tiny images and the narrow column layout with the Custom Skin. Is there something in the settings to check?

Many thanks in advance :)

Regards, 

Bas

**Comment by dudaster** [comment]
you need to add this to your css:

```
.ecs-post-loop .ast-article-post{
    width:100%;
}
```
