### ISSUE TITLE
Same Height doesn't work with "Make entire post a link" option

### ISSUE THREAD

**Issue by SandowMichaelMa** [dudaster/ele-custom-skin#739]
Hi,

I'm noticing that if you have option "Make entire post a link" enabled, the same height doesn't work properly. Without that option, it seems to work fine.

**Comment by AaronTriQ** [comment]
Thanks for noticing, was wondering why it wasn't working on some of my sites. Same problem here.

**Comment by frednetk** [comment]
Same issue also for me. 
Only way to fix now is to set min height to the loop, but hope to see and update soon to fix it.

Ele skin 3.15
Ele skin Pro 3.2.3
Elementor/elementor pro 3.6.4

**Comment by vollerempfang** [comment]
Hey Liviu @dudaster , is there any fix coming for this?
We've purchased the pro version for exactly the two features and it's really a bummer to see (after purchasing) that this is not working and there's no response since 19 days.

**Comment by Sergijus** [comment]
Same issue here, using all the latest versions and no other plugins on website, except LS cache which was deactivated.
![image](https://user-images.githubusercontent.com/43016562/165154898-01ef773d-b845-470c-8f89-77d13f654492.png)

**Comment by dudaster** [comment]
released 3.2.4 should fix the issue

**Comment by SandowMichaelMa** [comment]
@dudaster Issue still not fixed as far as I can tell. I turned off the Same Height option and then toggled it back on and it looks exactly the same. If I turn off the Make Entire Post a Link, Same Height works.

**Comment by dudaster** [comment]
Do you have ECS pro 3.2.5 installed?

**Comment by SandowMichaelMa** [comment]
Yes. All latest versions of everything.

If I toggle OFF "Make entire post a link", Same Height works. If I toggle it back on, it doesn't work. No amount of toggling these two settings fixes the issue.

**Comment by bislamovic** [comment]
If this can help: 


**Make entire post a link** having issue when loop item is having different background. In that case there is a part where that bacground color is not from top to bottom in shorter items:
<img width="584" alt="2022-07-21_11h05_27" src="https://user-images.githubusercontent.com/21058182/180176248-651c0a2f-d2ff-4297-a6c6-1b6394ed6ee1.png">

**Comment by frednetk** [comment]
Still not solved! 
ele custom skin 3.1.7
ele custom skin pro 3.2.4
with "make entire post as link", the same heigh doesn't work.

Also with latest elementor release, the button wrapper inside an archive widget, add an automatic margin on top, even if there is no margin inside the custom skin loop.
This doesn't happen with the slider activated
![custom_skin_margin](https://user-images.githubusercontent.com/102518514/189090481-2f62d85c-6956-4021-a5e8-215ceba18920.jpg)
![custom_skin-loop](https://user-images.githubusercontent.com/102518514/189090487-f7f69d03-181c-4337-8af0-e3dfd050598d.jpg)
![custom-skin-slider](https://user-images.githubusercontent.com/102518514/189090491-e2b799cf-e0e0-4516-9443-e13376d2e75a.jpg)



Elementor 3.7.4 and Pro 3.7.5
