### ISSUE TITLE
Compatibility Issue Between Elementor v3.26.0 and Elementor Custom Skin Pro

### ISSUE THREAD

**Issue by Gab1344** [dudaster/ele-custom-skin#949]
After updating Elementor to version 3.26.0, Elementor Custom Skin Pro triggers a Fatal Error related to the class Elementor\Core\Schemes\Color and the get_type() method. This issue arises when registering custom controls in skins, breaking the plugin's functionality. Please find the error message and the affected code snippet attached for review. We kindly request a fix or an update to ensure compatibility with the latest Elementor version.

**Comment by KatharineHolmes** [comment]
I'm having the same issue. :(

Edited to add: I had to disable the plug in to get a page to load. Otherwise it was a Critical Error.

**Comment by robertstaddon** [comment]
I'm experiencing the same issue! Here's the fatal error that I'm getting in my error logs:

PHP Fatal error:  Uncaught Error: Class "Elementor\Core\Schemes\Color" not found in /public_html/wp-content/plugins/ele-custom-skin-pro/skin/skin-custom.php:652
Stack trace:
#0 /public_html/wp-includes/class-wp-hook.php(324): {closure}()
#1 /public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#2 /public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /public_html/wp-content/plugins/ele-custom-skin/skins/skin-custom.php(53): do_action()
#4 /public_html/wp-includes/class-wp-hook.php(326): ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS->register_navigation_design_controls()
#5 /public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#6 /public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#7 /public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1690): do_action()
#8 /public_html/wp-content/plugins/elementor/includes/base/sub-controls-stack.php(200): Elementor\Controls_Stack->end_controls_section()
#9 /public_html/wp-content/plugins/elementor-pro/modules/posts/skins/skin-base.php(503): Elementor\Sub_Controls_Stack->end_controls_section()
#10 /public_html/wp-content/plugins/elementor-pro/modules/posts/skins/skin-base.php(58): ElementorPro\Modules\Posts\Skins\Skin_Base->register_design_layout_controls()
#11 /public_html/wp-content/plugins/elementor-pro/modules/posts/skins/skin-base.php(41): ElementorPro\Modules\Posts\Skins\Skin_Base->register_design_controls()
#12 /public_html/wp-includes/class-wp-hook.php(326): ElementorPro\Modules\Posts\Skins\Skin_Base->register_style_sections()
#13 /public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#14 /public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#15 /public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1690): do_action()
#16 /public_html/wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php(132): Elementor\Controls_Stack->end_controls_section()
#17 /public_html/wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php(64): ElementorPro\Modules\Posts\Widgets\Posts->register_query_section_controls()
#18 /public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2386): ElementorPro\Modules\Posts\Widgets\Posts->register_controls()
#19 /public_html/wp-content/plugins/elementor/includes/base/widget-base.php(1050): Elementor\Controls_Stack->init_controls()
#20 /public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(569): Elementor\Widget_Base->init_controls()
#21 /public_html/wp-content/plugins/elementor/includes/base/widget-base.php(184): Elementor\Controls_Stack->get_stack()
#22 /public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(314): Elementor\Widget_Base->get_stack()
#23 /public_html/wp-content/plugins/elementor/core/files/css/post.php(332): Elementor\Controls_Stack->get_controls()
#24 /public_html/wp-content/plugins/elementor/core/files/css/post.php(296): Elementor\Core\Files\CSS\Post->render_element_global_styles()
#25 /public_html/wp-content/plugins/elementor/core/files/css/post.php(226): Elementor\Core\Files\CSS\Post->render_styles()
#26 /public_html/wp-content/plugins/elementor/core/files/css/post.php(318): Elementor\Core\Files\CSS\Post->add_controls_stack_style_rules()
#27 /public_html/wp-content/plugins/elementor/core/files/css/post.php(297): Elementor\Core\Files\CSS\Post->render_element_styles()
#28 /public_html/wp-content/plugins/elementor/core/files/css/post.php(226): Elementor\Core\Files\CSS\Post->render_styles()
#29 /public_html/wp-content/plugins/elementor/core/files/css/post.php(318): Elementor\Core\Files\CSS\Post->add_controls_stack_style_rules()
#30 /public_html/wp-content/plugins/elementor/core/files/css/post.php(297): Elementor\Core\Files\CSS\Post->render_element_styles()
#31 /public_html/wp-content/plugins/elementor/core/files/css/post.php(178): Elementor\Core\Files\CSS\Post->render_styles()
#32 /public_html/wp-content/plugins/elementor/core/files/css/base.php(687): Elementor\Core\Files\CSS\Post->render_css()
#33 /public_html/wp-content/plugins/elementor/core/files/base.php(180): Elementor\Core\Files\CSS\Base->parse_content()
#34 /public_html/wp-content/plugins/elementor/core/files/css/base.php(133): Elementor\Core\Files\Base->update_file()
#35 /public_html/wp-content/plugins/elementor/core/files/css/base.php(229): Elementor\Core\Files\CSS\Base->update()
#36 /public_html/wp-content/plugins/elementor/core/files/css/post.php(201): Elementor\Core\Files\CSS\Base->enqueue()
#37 /public_html/wp-content/plugins/elementor/includes/frontend.php(695): Elementor\Core\Files\CSS\Post->enqueue()
#38 /public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php(193): Elementor\Frontend->enqueue_styles()
#39 /public_html/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager->enqueue_styles()
#40 /public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#41 /public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#42 /public_html/wp-includes/script-loader.php(2272): do_action()
#43 /public_html/wp-includes/class-wp-hook.php(324): wp_enqueue_scripts()
#44 /public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#45 /public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#46 /public_html/wp-includes/general-template.php(3064): do_action()
#47 /public_html/wp-content/themes/hello-elementor/header.php(24): wp_head()
#48 /public_html/wp-includes/template.php(810): require_once('/home/bridgetoc...')
#49 /public_html/wp-includes/template.php(745): load_template()
#50 /public_html/wp-includes/general-template.php(48): locate_template()
#51 /public_html/wp-content/plugins/elementor/modules/page-templates/templates/header-footer.php(9): get_header()
#52 /public_html/wp-includes/template-loader.php(106): include('/home/bridgetoc...')
#53 /public_html/wp-blog-header.php(19): require_once('/home/bridgetoc...')
#54 /public_html/index.php(17): require('/home/bridgetoc...')
#55 {main}
  thrown in /public_html/wp-content/plugins/ele-custom-skin-pro/skin/skin-custom.php on line 652

**Comment by 1000camels** [comment]
I commented out lines 651-654 in ele-custom-skin-pro/skin/skin-custom.php, which avoids the issue. I just needed to get my site up again.

// 'scheme' => [
// 	'type' => Elementor\Core\Schemes\Color::get_type(),
// 	'value' => Elementor\Core\Schemes\Color::COLOR_4,
// ],

I believe 'scheme' is no longer an elementor property for add_control and should likely use 'global' and/or 'default'.

**Comment by 1000camels** [comment]
Actually, I replaced those lines with the following and it seemed to work

				'global' => [
					'default' => \Elementor\Core\Kits\Documents\Tabs\Global_Colors::COLOR_PRIMARY,
				],

**Comment by chaitanya-ap** [comment]
> Actually, I replaced those lines with the following and it seemed to work
> 
> ```
> 			'global' => [
> 				'default' => \Elementor\Core\Kits\Documents\Tabs\Global_Colors::COLOR_PRIMARY,
> 			],
> ```

Good suggestion @1000camels . Thanks. It worked for me as well.

**Comment by dbfischer** [comment]
Same issue. Thank you @1000camels . It works.

**Comment by laraignee** [comment]
Same issue ... 😒

**Comment by asansano** [comment]
@1000camels works for us too! and yes it was removed in 3.26 'Tweak: Removed elementor/core/schemes'
https://wordpress.org/plugins/elementor/#developers

**Comment by nndesignac** [comment]
@1000camels Thank you, it works!

**Comment by FrankWalle** [comment]
Works... Thanks @1000camels 
Will this be part of one of the next updates?
:-)

**Comment by 1000camels** [comment]
I am not one of the developers so I cannot say

**Comment by Gab1344** [comment]
The temporary solution provided by @1000camels works simply to keep the site functional, but Elementor Pro is not working properly in my case. I have developed loops to be displayed using the Posts widget, but the carousel element does not display correctly.

This issue seems to be caused by a malfunction in the Elementor Custom Skin Pro plugin. We kindly request that the developers review this to ensure everything works as expected.

Additionally, has anyone else encountered a similar issue where developing a carousel results in it not displaying correctly or appearing "broken"?

**Comment by FrankWalle** [comment]
Had the same thing... during update the Ele Custom Skin Pro was disabled... enabled it again and everything works.

**Comment by Gab1344** [comment]
I’ve been in contact with the Elementor Pro support team, and they mentioned that Dutaster is aware of the issue and is currently working on a compatibility solution for the latest version of Elementor. To make it work, I was advised to roll back to a previous version of both Elementor and Elementor Pro to retain all functionalities without changing any code. I applied their suggested solutions, and the plugin is now working correctly. Now, we just have to wait for a new version of Elementor Custom Skin Pro.

**Comment by atiweb** [comment]
More info about the cause of the issue, breaking changes on Elementor 3.26.
Details in:
https://developers.elementor.com/elementor-3-26-developers-update/
https://developers.elementor.com/docs/deprecations/complex-example/

**Comment by PauKokura** [comment]
Same here. Downgraded. Will wait for the update.

**Comment by dudaster** [comment]
The update is up!

**Comment by KatharineHolmes** [comment]
Thanks, @dudaster!

**Comment by drthorogood** [comment]
The update fixed the pro version but what about the free version? It throws a critical error when updating Elementor.

**Comment by Gab1344** [comment]
The update only fixes the site from looking broken, but the sliders are still not functioning correctly. They should continue reviewing.

**Comment by ottomarciano1234** [comment]
I fixed it installing Elementor 3.23, newest versions doesn't work, it might be caused by an old version of your theme. I hope this help you.

**Comment by MatanSaban** [comment]
dont work with latest elementor or previous versions..

**Comment by sharif-elshobkshy** [comment]
Hi,

Shouldn't this ticket be open?
The issue still exist.

Thanks.

**Comment by MatanSaban** [comment]
Yes it should
